[package]
name = "ray-tracer-challenge"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "3.0", features = ["derive", "cargo"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
